"""empty message

Revision ID: 924128a563dc
Revises: c986be430e02
Create Date: 2019-12-03 12:24:48.377573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924128a563dc'
down_revision = 'c986be430e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_filled', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_filled')
    # ### end Alembic commands ###
